eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9211
spring:
  application:
    name: sass-zipkin
  sleuth:
    enabled: true

management:
  security:
    enabled: false