spring:
  application.name: sass-turbine
server:
  port: 8779
security.basic.enabled: false
turbine:
  aggregator:
    # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    clusterConfig: SASS-ZUUL,SASS-ZIPKIN,SASS-SERVICE-WEB,SASS-SERVICE-MANAGER,SASS-SERVICE-SYSCONFIG,SASS-SERVICE-ENTRANCE,SASS-SERVICE-RESIDENT,SASS-SERVICE-ZONE
  # 配置Eureka中的serviceId列表，表明监控哪些服务
  appConfig: sass-zuul,sass-service-zipkin,sass-service-web,sass-service-manager,sass-service-sysconfig,sass-service-entrance,sass-service-resident,sass-service-zone
#  clusterNameExpression: metadata['cluster']
  # 1. clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
  # 2. 当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
  # 3. 当clusterNameExpression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
logging:
  file: /Users/lokizero00/Documents/java_proj/sass-logs/${spring.application.name}-${server.port}.log
  level:
    root: INFO
    #    org.springframework.web: DEBUG
    com.loki.sass: DEBUG